### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by Official-BReep** [MKFeuer/Weihnachtsgeschenke#1]
wenn man den Source Code der Programme nicht einsehen kann, dann wird denk ich niemand das herunterladen

**Comment by MKFeuer** [comment]
das sind halt android apps und die dateien sind zum direckten installieren

**Comment by Official-BReep** [comment]
Ich weiß, aber niemand lädt sich freiwillig einen Virus runter und das ist halt der erste gedanke, wenn kein Source code da ist

**Comment by MKFeuer** [comment]
OK hast du dann nen Vorschlag was man stattdessen machen könnte, weil dass mit den Android Apps wede ich in die readme rein schreiben, nur komme ich an den surcecode der apks noch dran

**Comment by Official-BReep** [comment]
wieso kommst du da nicht dran?

**Comment by MKFeuer** [comment]
Weil ich das über eine Website gemacht habe und die das gleich als APK raus geworfen hat. 

Wir haben dort mit codeblöcken wie in Scratch gearbeitet
